# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "022970402fe6201f671a1fffed454974"
application_url = "https://31f74bcd7f90.ngrok.app"
embedded = true
name = "size-buddy"
handle = "size-buddy-v6-testing"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://31f74bcd7f90.ngrok.app/api/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products read_products write_customers read_customers read_themes write_themes"

[auth]
redirect_urls = [
      "https://31f74bcd7f90.ngrok.app/api/auth/callback",
      "https://31f74bcd7f90.ngrok.app/api/auth/exit-iframe"
]

[pos]
embedded = false

[app_proxy]
  url = "https://31f74bcd7f90.ngrok.app"
prefix = "apps"
subpath = "size-buddy"
